### ISSUE TITLE
Error nimbro make:  undefined reference to rviz::MarkerDisplay::MarkerDisplay()

### ISSUE THREAD

**Issue by tienanh08** [AIS-Bonn/humanoid_op_ros#1]
hi,
I implemented following installation.md but i get error:

`CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o: In function `MyMarkerDisplay::MyMarkerDisplay()':
/home/tienanh/catkin_ws/src/ROS-IGUS-System/src/nimbro/tools/trajectory_editor_2/src/mymarkerdisplay.cpp:3: undefined reference to `rviz::MarkerDisplay::MarkerDisplay()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o: In function `MyMarkerDisplay::update(float, float)':
/home/tienanh/catkin_ws/src/ROS-IGUS-System/src/nimbro/tools/trajectory_editor_2/src/mymarkerdisplay.cpp:10: undefined reference to `rviz::MarkerDisplay::update(float, float)'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o: In function `MyMarkerDisplay::~MyMarkerDisplay()':
/home/tienanh/catkin_ws/src/ROS-IGUS-System/src/nimbro/tools/trajectory_editor_2/include/trajectory_editor_2/mymarkerdisplay.h:11: undefined reference to `rviz::MarkerDisplay::~MarkerDisplay()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o: In function `~MyMarkerDisplay':
/home/tienanh/catkin_ws/src/ROS-IGUS-System/src/nimbro/tools/trajectory_editor_2/include/trajectory_editor_2/mymarkerdisplay.h:11: undefined reference to `rviz::MarkerDisplay::~MarkerDisplay()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTI15MyMarkerDisplay[_ZTI15MyMarkerDisplay]+0x10): undefined reference to `typeinfo for rviz::MarkerDisplay'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x10): undefined reference to `rviz::MarkerDisplay::metaObject() const'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x18): undefined reference to `rviz::MarkerDisplay::qt_metacast(char const*)'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x20): undefined reference to `rviz::MarkerDisplay::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x108): undefined reference to `rviz::MarkerDisplay::load(rviz::Config const&)'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x168): undefined reference to `rviz::MarkerDisplay::setTopic(QString const&, QString const&)'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x178): undefined reference to `rviz::MarkerDisplay::reset()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x190): undefined reference to `rviz::MarkerDisplay::onInitialize()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x198): undefined reference to `rviz::MarkerDisplay::onEnable()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x1a0): undefined reference to `rviz::MarkerDisplay::onDisable()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x1b0): undefined reference to `rviz::MarkerDisplay::fixedFrameChanged()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x1c0): undefined reference to `rviz::MarkerDisplay::subscribe()'
CMakeFiles/trajectory_editor_2.dir/src/mymarkerdisplay.cpp.o:(.rodata._ZTV15MyMarkerDisplay[_ZTV15MyMarkerDisplay]+0x1c8): undefined reference to `rviz::MarkerDisplay::unsubscribe()'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/tienanh/catkin_ws/src/ROS-IGUS-System/devel/lib/trajectory_editor_2/trajectory_editor_2] Error 1
make[1]: *** [nimbro/tools/trajectory_editor_2/CMakeFiles/trajectory_editor_2.dir/all] Error 2
make: *** [all] Error 2
`
Can you help me?
Thanks

**Comment by hfarazi** [comment]
It was because of some changes in RViz API since we released. The latest commit fixes the problem https://github.com/AIS-Bonn/humanoid_op_ros/commit/cd86198d55abc8fb30ab1050eb8e68701294499b.
